### ISSUE TITLE
`hbbft` Integration Meta-Thread

### ISSUE THREAD

**Issue by c0gent** [poanetwork/parity-ethereum#8]
This will be updated to contain the latest information about the status of [`hbbft`](https://github.com/poanetwork/hbbft) integration into Parity.

The broad overview is as follows:

- [ ] Get hbbft fully functioning within Parity in a forked version. This make include changes which breaks Parity for non-hbbft networks.
  - [ ] Lay the foundations
    - [ ] Update deprecated dependencies needed within hydrabadger/hbbft. This must be done now to reduce the amount of future work required (to keep the technical debt to a bare minimum). Because this work will also be appreciated by the Parity maintainers, it is also a good place to begin what will likely be a long relationship of contribution.
      - [ ] Replace use of `tokio_core` (deprecated) with `tokio`.
        - [X] `jsonrpc`: https://github.com/paritytech/jsonrpc/pull/303
          - [X] `parity_tokio_ipc`: https://github.com/NikVolf/parity-tokio-ipc/pull/9
            - [X] `tokio-named-pipes`: https://github.com/NikVolf/tokio-named-pipes/pull/1
      - [ ] Remainder of Parity crates and modules (will update with full list)...
  - [X] Config integration
  - [ ] Engine integration
    - [X] Add a Placeholder
  - [ ] Miner integration
    - [ ] ...
  - [ ] Network integration
    - [ ] (this may be put off until non-breaking integration phase) ...
  - [ ] Much, much more (will update). 
- [ ] Full non-breaking integration.
  - [ ] ...

As I have a clearer picture of precisely what needs to be done for each 'chunk' of work I will coordinate with anyone willing to help.

**Comment by DemiMarie** [comment]
Is this still being worked on? @igorbarinov
